name: clipsandstyles2
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.2
  firebase_core: ^3.6.0
  geolocator: ^13.0.1
  camera: ^0.11.0+2
  app_settings: ^5.1.1
  permission_handler: ^11.3.1
  flutter_local_notifications: ^19.0.0
  provider: ^6.1.2
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  dotted_border: ^2.1.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  firebase_storage: ^12.3.3
  video_player: ^2.9.2
  chewie: ^1.8.5
  fl_chart: ^0.70.2
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  hive_flutter: ^1.1.0
  calendar_date_picker2: ^2.0.0
  pdf: ^3.11.2
  excel: ^4.0.6
  open_file: ^3.5.10
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  collection: ^1.18.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/Frame4.svg
    - assets/Frame4.png
    - assets/Frame5.png
    - assets/Frame6.png
    - assets/Google.svg
    - assets/customer.png
    - assets/business.png
    - assets/Frame8.png
    - assets/appleicon.svg
    - assets/Google.svg
    - assets/Facebookicon.svg
    - assets/Emailicon.svg
    - assets/email.svg
    - assets/location.jpg
    - assets/location1.jpg
    - assets/locationn.png
    - assets/camera.png
    - assets/notification.png
    - assets/notification.jpg
    - assets/notification1.jpg
    - assets/default.svg
    - assets/Businessprofile.jpg
    - assets/notificationicon.svg
    - assets/barber.jpg
    - assets/salon.jpg
    - assets/spa.jpg
    - assets/Nailtech.jpg
    - assets/Dreadlocks.jpg
    - assets/Makeup.jpg
    - assets/TatooandPiercing.jpg
    - assets/eyebrows.jpg
    - assets/congratulations.png
    - assets/loyaltypoints.png
  



  fonts:
  - family: Kavoon
    fonts:
      - asset: assets/Kavoon-Regular.ttf
   
      


